function serializeForSingleQuotes(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

export function buildBookmarklet(appOrigin: string) {
  const origin = serializeForSingleQuotes(appOrigin.replace(/\/$/, ""));

  return `javascript:(function(){var origin='${origin}';var hostId='vora-whisper-host';var existing=document.getElementById(hostId);if(existing){existing.remove();return;}var host=document.createElement('div');host.id=hostId;host.style.position='fixed';host.style.right='16px';host.style.bottom='16px';host.style.zIndex='2147483647';var frame=document.createElement('iframe');frame.src=origin+'/widget?embed=1';frame.title='Vora-Whisper';frame.style.width='248px';frame.style.height='118px';frame.style.border='0';frame.style.borderRadius='18px';frame.style.boxShadow='0 16px 48px rgba(15,20,25,.18)';frame.style.background='#fff';frame.allow='microphone';host.appendChild(frame);document.body.appendChild(host);function showToast(message){var toast=document.createElement('div');toast.textContent=message;toast.style.position='fixed';toast.style.right='16px';toast.style.bottom='146px';toast.style.padding='10px 12px';toast.style.background='#0F1419';toast.style.color='#fff';toast.style.font='12px sans-serif';toast.style.borderRadius='10px';toast.style.zIndex='2147483647';document.body.appendChild(toast);setTimeout(function(){toast.remove();},2200);}function insertText(text){var active=document.activeElement;if(!active){showToast('Transcript copied. Paste manually.');return false;}if(active instanceof HTMLInputElement||active instanceof HTMLTextAreaElement){var start=active.selectionStart??active.value.length;var end=active.selectionEnd??active.value.length;active.focus();active.setRangeText(text,start,end,'end');active.dispatchEvent(new Event('input',{bubbles:true}));active.dispatchEvent(new Event('change',{bubbles:true}));return true;}if(active.isContentEditable){active.focus();if(document.execCommand){document.execCommand('insertText',false,text);return true;}}return false;}window.addEventListener('message',async function(event){if(!event.data||event.data.source!=='vora-whisper'){return;}if(event.data.type==='VORA_INSERT_TRANSCRIPT'){var inserted=insertText(event.data.text||'');if(!inserted&&navigator.clipboard&&navigator.clipboard.writeText){try{await navigator.clipboard.writeText(event.data.text||'');showToast('Transcript copied. Paste manually.');}catch(error){showToast('Transcript ready. Paste manually.');}}else if(inserted){showToast('Transcript inserted.');}}if(event.data.type==='VORA_WIDGET_CLOSE'){host.remove();}if(event.data.type==='VORA_WIDGET_PIN'){var pinnedTop=host.style.top==='16px';host.style.top=pinnedTop?'':'16px';host.style.bottom=pinnedTop?'16px':'';}});})();`;
}
